management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: warn
    com:
      netflix:
        hystrix: trace
spring:
  groovy:
    template:
      expose-request-attributes:
server:
  tomcat:
    redirect-context-root:
