spring:
  datasource:
    url: jdbc:h2:${user.dir}/msdb
    username: SA
    ## Default password for h2 DB is empty.
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
