spring:
  datasource:
    #url: jdbc:h2:${user.dir}/msdb
    url: jdbc:h2:tcp://192.168.99.1:9092/msdb
    username: SA
    ## Default password for h2 DB is empty.
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
