spring:
  application:
    # By default Spring Cloud registers the service to Eureka with a slug containing the application name.
    name: planets-service

logging:
  level:
    root: INFO
    org:
      springframework:
        core:
          env: INFO
    com:
      netflix:
        discovery: TRACE

server:
  port: 44444

eureka:
  client:
    serviceUrl:
      # The URL to the Eureka's API.
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      # ???
      enabled: true

