spring:
  application:
    name: zuul-service

## Zuul routes.
#zuul:
#  ignoredServices: '*'
#  routes:
#    trips:
#      path: /trips/**
#
#      # Uses 'disovoery' instead of fixed IP.
#      serviceId: TRIP-SERVICE

# Ribbon is auto integrated with Zuul and for this exercise we are not using that.
ribbon:
  eureka:
    enabled: true

# Port on which zuul will bind
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
