spring:
  application:
    name: planets-service

logging:
  level:
    root: INFO
    org:
      springframework:
        core:
          env: INFO
    com:
      netflix:
        discovery: TRACE

server:
  port: 44444

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

