# Refer to https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# for a comprehensive list of available properties.

# EMBEDDED SERVER CONFIGURATION

# Embedded HTTP Server
server:
  # Port.
  port: 9090
  # Network address to which the server should bind. Leave blank to bind to all IPs
  address:
